### PR TITLE
Address YouTube and Turbolinks issues

### LINKED ISSUE #710: Videos wonky after pressing back button
"when going back to a run page via the back button, the seek via click on the splits bar doesn't work"

Reported from this Discord message: https://discordapp.com/channels/361957211318124555/535862834261655593/733219640796381216

### PR DESCRIPTION
**Pull request by moorecp**
Closes #710 

This fixes the issue where we were having to poll to see if YouTube was ready due to Turbolinks issues. Additionally, it addresses #710 and fixes problems where a YouTube player wouldn't be seen as attached to the DOM when not performing a full page load.

### CODE REVIEW

File: app/javascript/youtube.js [hunk 1]
```diff
@@ -1,6 +1,7 @@
 const async = require('async')
 
 window.onYouTubeIframeAPIReady = () => {
+  setupYouTubeVideos()
   return true
 }
```
Comment (glacials) [inline app/javascript/youtube.js:6]: Are we able to collapse `onYouTubeIframeAPIReady` and `setupYouTubeVideos` into a single function?

Comment (moorecp) [reply app/javascript/youtube.js]: I don't see why not.
